# Generated by Django 6.0.2 on 2026-02-15 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('total_amount', models.FloatField(default=0)),
                ('amount_paid', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note_500', models.IntegerField(default=0)),
                ('note_200', models.IntegerField(default=0)),
                ('note_100', models.IntegerField(default=0)),
                ('note_50', models.IntegerField(default=0)),
                ('note_20', models.IntegerField(default=0)),
                ('note_10', models.IntegerField(default=0)),
                ('note_5', models.IntegerField(default=0)),
                ('note_2', models.IntegerField(default=0)),
                ('note_1', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('subtotal', models.FloatField()),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bill.bill')),
            ],
        ),
    ]
